### ISSUE TITLE
gitignore readme.txt and svn ignore readme.md

### ISSUE THREAD

**Issue by twoelevenjay** [kasparsd/wp-deploy#3]
I would like to be able to have both a readme.txt (for wordpress.org) and a readme.md (for github) in my your-plugin-slug > git directory. I would like git push to ignore the readme.txt and ./tag.sh VERSION and ./deploy.sh VERSION to ignore the readme.md. Does anyone have any suggestions on how I could achieve this?

**Comment by kasparsd** [comment]
@twoelevenjay The script assumes that you have a `.md` readme which is converted to `.txt` and deleted  during SVN commits, see https://github.com/kasparsd/wp-deploy/blob/master/deploy.sh#L45-L48

**Comment by twoelevenjay** [comment]
Wow thank you, I had both files like a fool lol. I am very grateful for this repo thank you!
